#!/usr/bin/env bash
# a bash script ot display chinese badluck numbers

i=1

while [ $i -le 20 ]
do 
	echo "$i"
	case $i in 
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from italy";;
	esac
	((i++))
done
